// lib/storage.js — Persistent knowledge graveyard
// Saves and retrieves knowledge documents from ~/.openclaw/zombie-hoard/

import fs from 'fs';
import path from 'path';
import os from 'os';
import crypto from 'crypto';

// ── Paths ──────────────────────────────────────────────────────────────────────
const BASE_DIR = process.env.ZOMBIE_STORAGE_DIR
  || path.join(os.homedir(), '.openclaw', 'zombie-hoard');

const KNOWLEDGE_DIR = path.join(BASE_DIR, 'knowledge');
const GRAVEYARD_FILE = path.join(BASE_DIR, 'graveyard.json');
const MAX_GRAVEYARD_ENTRIES = 500;

// ── Helpers ────────────────────────────────────────────────────────────────────
function ensureDirs() {
  fs.mkdirSync(KNOWLEDGE_DIR, { recursive: true, mode: 0o700 });
}

function slugify(topic) {
  let slug = topic
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 80);

  // FIX: if slug is empty (e.g. CJK/Arabic input), use a hash-based slug
  if (!slug || slug.length < 2) {
    slug = 'topic-' + crypto.createHash('sha256').update(topic).digest('hex').substring(0, 16);
  }
  return slug;
}

function loadGraveyard() {
  try {
    const raw = fs.readFileSync(GRAVEYARD_FILE, 'utf-8');
    // Guard against corrupted/oversized JSON
    if (raw.length > 10_000_000) {
      console.error('Warning: graveyard.json exceeds 10MB, may be corrupted');
    }
    return JSON.parse(raw);
  } catch {
    return { entries: [], totalRuns: 0 };
  }
}

function saveGraveyard(data) {
  ensureDirs();
  // Enforce max entries to prevent unbounded growth
  if (data.entries.length > MAX_GRAVEYARD_ENTRIES) {
    data.entries = data.entries.slice(0, MAX_GRAVEYARD_ENTRIES);
  }
  fs.writeFileSync(GRAVEYARD_FILE, JSON.stringify(data, null, 2), { encoding: 'utf-8', mode: 0o600 });
}

// ── Build the full knowledge markdown document ─────────────────────────────────
function buildDocument(topic, zombieResults, synthesisResult, meta) {
  const now = new Date().toISOString();
  const zombieTable = zombieResults.map(r =>
    `| ${r.emoji} ${r.name} | ${r.undeadIndex}/10 | ${r.duration}s | ${r.failed ? '❌ Failed' : '✅'} |`
  ).join('\n');

  const zombieSections = zombieResults
    .filter(r => !r.failed)
    .map(r => `## ${r.emoji} ${r.name}\n*Hunger: ${r.hunger}*\n\n${r.content}`)
    .join('\n\n---\n\n');

  const infectedList = synthesisResult.infectedTopics.length > 0
    ? synthesisResult.infectedTopics.map(t => `- \`${t}\``).join('\n')
    : '- *(none detected)*';

  return `# 🧟 Zombie Hoard Knowledge: ${topic}

> *Raised by the hoard on ${now}*
> **Hoard Score:** ${synthesisResult.hoardScore}/10 | **Zombies deployed:** ${zombieResults.length} | **Total duration:** ${meta.totalDuration}s

---

## ☠️ Necromancer Synthesis

${synthesisResult.synthesis}

---

## 🪦 Zombie Deployment Log

| Zombie | Undead Index | Duration | Status |
|--------|-------------|----------|--------|
${zombieTable}

---

## 🧟 Individual Zombie Reports

${zombieSections}

---

## 🦠 Infected Topics (Explore Next)

${infectedList}

---

*Generated by [zombie-hoard](https://github.com/asock/zombie-hoard) — an OpenClaw skill by hellsy.net*
`;
}

// ── Public API ────────────────────────────────────────────────────────────────
export const storage = {
  save(topic, zombieResults, synthesisResult, meta = {}) {
    ensureDirs();
    const slug = slugify(topic);
    const filename = `${slug}.md`;
    const filepath = path.join(KNOWLEDGE_DIR, filename);

    const document = buildDocument(topic, zombieResults, synthesisResult, {
      totalDuration: meta.totalDuration || '?',
      ...meta,
    });
    fs.writeFileSync(filepath, document, { encoding: 'utf-8', mode: 0o600 });

    // Update graveyard index — store RELATIVE filename, not absolute path (portability fix)
    const graveyard = loadGraveyard();
    graveyard.totalRuns = (graveyard.totalRuns || 0) + 1;

    const existingIdx = graveyard.entries.findIndex(e => e.slug === slug);
    const entry = {
      topic,
      slug,
      filename,
      hoardScore: synthesisResult.hoardScore,
      zombieCount: zombieResults.length,
      infectedTopics: synthesisResult.infectedTopics,
      lastRun: new Date().toISOString(),
      runCount: existingIdx >= 0 ? (graveyard.entries[existingIdx].runCount || 1) + 1 : 1,
    };

    if (existingIdx >= 0) {
      graveyard.entries[existingIdx] = entry;
    } else {
      graveyard.entries.push(entry);
    }

    graveyard.entries.sort((a, b) => new Date(b.lastRun) - new Date(a.lastRun));
    saveGraveyard(graveyard);

    return { filepath, slug };
  },

  // Resolve a graveyard entry's filename to full path.
  // Always recomputes from KNOWLEDGE_DIR + filename and rejects any
  // filename containing a path separator or traversal segment, so a
  // tampered graveyard.json cannot point fs operations outside the dir.
  resolveFilepath(entry) {
    const name = entry.filename;
    if (typeof name !== 'string' || name.length === 0 || name.includes('/') || name.includes('\\') || name.includes('..')) {
      throw new Error(`Refusing unsafe knowledge filename: ${name}`);
    }
    return path.join(KNOWLEDGE_DIR, name);
  },

  recall(topic) {
    const graveyard = loadGraveyard();
    const slug = slugify(topic);

    let entry = graveyard.entries.find(e => e.slug === slug);

    if (!entry) {
      entry = graveyard.entries.find(e =>
        e.slug.includes(slug) || slug.includes(e.slug) ||
        e.topic.toLowerCase().includes(topic.toLowerCase()) ||
        topic.toLowerCase().includes(e.topic.toLowerCase())
      );
    }

    if (!entry) return null;

    try {
      const filepath = this.resolveFilepath(entry);
      const content = fs.readFileSync(filepath, 'utf-8');
      return { entry, content, filepath };
    } catch {
      return { entry, content: null, readError: true };
    }
  },

  listGraveyard() {
    return loadGraveyard();
  },

  /**
   * Purge a topic from the graveyard (delete knowledge file + index entry)
   * Returns { purged: true, topic } or { purged: false, reason }
   */
  purge(topic) {
    const graveyard = loadGraveyard();
    const slug = slugify(topic);

    const idx = graveyard.entries.findIndex(e =>
      e.slug === slug ||
      e.topic.toLowerCase() === topic.toLowerCase()
    );

    if (idx === -1) {
      return { purged: false, reason: `No knowledge found for "${topic}"` };
    }

    const entry = graveyard.entries[idx];
    const filepath = this.resolveFilepath(entry);

    // Remove the knowledge file
    try {
      if (fs.existsSync(filepath)) {
        fs.unlinkSync(filepath);
      }
    } catch {
      // File already gone, that's fine
    }

    // Remove from index
    const purgedTopic = entry.topic;
    graveyard.entries.splice(idx, 1);
    saveGraveyard(graveyard);

    return { purged: true, topic: purgedTopic };
  },

  /**
   * Export a topic's knowledge as JSON
   */
  exportJSON(topic) {
    const recalled = this.recall(topic);
    if (!recalled || !recalled.content) return null;

    return {
      topic: recalled.entry.topic,
      slug: recalled.entry.slug,
      hoardScore: recalled.entry.hoardScore,
      runCount: recalled.entry.runCount,
      lastRun: recalled.entry.lastRun,
      infectedTopics: recalled.entry.infectedTopics,
      markdownContent: recalled.content,
    };
  },

  loadPriorKnowledge(topic) {
    const recalled = this.recall(topic);
    if (!recalled || !recalled.content) return null;

    const { entry, content } = recalled;

    const synthMatch = content.match(
      /## ☠️ Necromancer Synthesis\s*\n([\s\S]*?)(?:\n---|\n## 🪦)/
    );
    const synthesis = synthMatch ? synthMatch[1].trim() : null;
    if (!synthesis) return null;

    const zombieSections = [];
    const zombieRegex = /## 🧟 Individual Zombie Reports\s*\n([\s\S]*?)(?:\n---\s*\n## |$)/;
    const zombieBlockMatch = content.match(zombieRegex);
    if (zombieBlockMatch) {
      const block = zombieBlockMatch[1];
      const sectionRegex = /## ([^\n]+)\n[\s\S]*?\n([\s\S]*?)(?=\n## |\n---\s*\n## |$)/g;
      let m;
      while ((m = sectionRegex.exec(block)) !== null) {
        const header = m[1].trim();
        const body = m[2].trim().substring(0, 800);
        if (body.length > 50) zombieSections.push({ header, body });
      }
    }

    return {
      runCount: entry.runCount,
      hoardScore: entry.hoardScore,
      lastRun: entry.lastRun,
      synthesis,
      zombieSections,
    };
  },

  stats() {
    const graveyard = loadGraveyard();
    return {
      totalTopics: graveyard.entries.length,
      totalRuns: graveyard.totalRuns || 0,
      storageDir: BASE_DIR,
      knowledgeDir: KNOWLEDGE_DIR,
    };
  },
};
