// lib/storage.js — Persistent knowledge graveyard.
//
// v3.0 changes:
//   • Persists STRUCTURED claims (with section + source citations) alongside
//     the rendered markdown, in a sidecar JSON file. This is what makes
//     "compounding knowledge" actually compound: prior runs leave behind
//     queryable claims, not prose blobs that the next run has to re-parse.
//   • The graveyard index now stores objective metrics (sources cited,
//     grounding ratio, sections covered, claim count) instead of self-graded
//     "Hoard Score" / "Undead Index" theatre.
//   • The legacy v2.0 markdown loader is kept as a fallback so an existing
//     graveyard from v2.0 still resolves on `recall`.

import fs from 'fs';
import path from 'path';
import os from 'os';
import crypto from 'crypto';
import { SECTIONS, SECTION_BY_ID } from './research.js';

// ── Paths ──────────────────────────────────────────────────────────────────────
const BASE_DIR =
  process.env.ZOMBIE_STORAGE_DIR || path.join(os.homedir(), '.openclaw', 'zombie-hoard');
const KNOWLEDGE_DIR = path.join(BASE_DIR, 'knowledge');
const CLAIMS_DIR = path.join(BASE_DIR, 'claims');
const GRAVEYARD_FILE = path.join(BASE_DIR, 'graveyard.json');
const MAX_GRAVEYARD_ENTRIES = 500;

// ── Helpers ────────────────────────────────────────────────────────────────────
function ensureDirs() {
  fs.mkdirSync(KNOWLEDGE_DIR, { recursive: true, mode: 0o700 });
  fs.mkdirSync(CLAIMS_DIR, { recursive: true, mode: 0o700 });
}

function slugify(topic) {
  let slug = (topic || '')
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
    .substring(0, 80);
  if (!slug || slug.length < 2) {
    slug =
      'topic-' +
      crypto.createHash('sha256').update(topic || '').digest('hex').substring(0, 16);
  }
  return slug;
}

function loadGraveyard() {
  try {
    const raw = fs.readFileSync(GRAVEYARD_FILE, 'utf-8');
    if (raw.length > 10_000_000) {
      console.error('Warning: graveyard.json exceeds 10MB, may be corrupted');
    }
    const data = JSON.parse(raw);
    if (!data || typeof data !== 'object') return { entries: [], totalRuns: 0 };
    if (!Array.isArray(data.entries)) data.entries = [];
    if (typeof data.totalRuns !== 'number') data.totalRuns = 0;
    return data;
  } catch {
    return { entries: [], totalRuns: 0 };
  }
}

function saveGraveyard(data) {
  ensureDirs();
  if (data.entries.length > MAX_GRAVEYARD_ENTRIES) {
    data.entries = data.entries.slice(0, MAX_GRAVEYARD_ENTRIES);
  }
  fs.writeFileSync(GRAVEYARD_FILE, JSON.stringify(data, null, 2), {
    encoding: 'utf-8',
    mode: 0o600,
  });
}

// ── Path safety ───────────────────────────────────────────────────────────────
function safeFilename(name) {
  if (
    typeof name !== 'string' ||
    name.length === 0 ||
    name.includes('/') ||
    name.includes('\\') ||
    name.includes('..')
  ) {
    throw new Error(`Refusing unsafe filename: ${name}`);
  }
  return name;
}

function knowledgePath(filename) {
  return path.join(KNOWLEDGE_DIR, safeFilename(filename));
}

function claimsPath(filename) {
  return path.join(CLAIMS_DIR, safeFilename(filename));
}

// ── Markdown rendering ────────────────────────────────────────────────────────
function renderMarkdown(topic, result, meta) {
  const now = new Date().toISOString();
  const m = result.metrics;
  const grounded = m.grounding_ratio;
  const sources =
    result.sources && result.sources.length > 0
      ? result.sources
          .map((s) => `${s.idx}. [${s.title}](${s.url}) *(${s.kind})*`)
          .join('\n')
      : '*No sources fetched — this run was ungrounded.*';

  const diffBlock =
    meta.diff && (meta.diff.added || meta.diff.removed)
      ? `\n## 🩻 Diff vs Prior Run\n\n` +
        `- **Added claims:** ${meta.diff.added}\n` +
        `- **Removed claims:** ${meta.diff.removed}\n` +
        `- **Kept claims:** ${meta.diff.kept}\n\n` +
        (meta.diff.added_claims?.length
          ? `### New since last run\n` +
            meta.diff.added_claims
              .map((c) => `- (${c.section}) ${c.text}`)
              .join('\n') +
            '\n'
          : '') +
        (meta.diff.removed_claims?.length
          ? `\n### Dropped since last run\n` +
            meta.diff.removed_claims
              .map((c) => `- (${c.section}) ${c.text}`)
              .join('\n') +
            '\n'
          : '')
      : '';

  return `# 🧟 Zombie Hoard: ${topic}

> *Raised on ${now}*
> **Grounding:** ${m.sources_cited}/${m.sources_fetched} sources cited · **Sections:** ${m.sections_covered}/${m.sections_total} covered · **Claims:** ${m.claims_grounded}/${m.claims_extracted} grounded (${(grounded * 100).toFixed(0)}%) · **Duration:** ${meta.totalDuration || '?'}s

---

## 📚 Sources

${sources}

---

${result.markdown}
${diffBlock}
---

*Generated by [zombie-hoard v3.0](https://github.com/asock/zombie-hoard) — one zombie in a trenchcoat, doing it honestly.*
`;
}

// ── Public API ────────────────────────────────────────────────────────────────
export const storage = {
  /**
   * Persist a research result. Writes BOTH a markdown document (for humans)
   * and a structured JSON sidecar (for re-run diffing and machine queries).
   */
  save(topic, result, meta = {}) {
    ensureDirs();
    const slug = slugify(topic);
    const mdName = `${slug}.md`;
    const jsonName = `${slug}.json`;
    const mdPath = knowledgePath(mdName);
    const jsonPath = claimsPath(jsonName);

    // 1. Markdown for humans
    const document = renderMarkdown(topic, result, meta);
    fs.writeFileSync(mdPath, document, { encoding: 'utf-8', mode: 0o600 });

    // 2. Structured JSON sidecar for the machine
    const graveyard = loadGraveyard();
    const existing = graveyard.entries.find((e) => e.slug === slug);
    const runCount = (existing?.runCount || 0) + 1;
    const lastRun = new Date().toISOString();

    const sidecar = {
      schemaVersion: 1,
      topic,
      slug,
      lastRun,
      runCount,
      sources: result.sources || [],
      sections: result.sections || {},
      claims: result.claims || [],
      executive: result.executive || null,
      contradictions: result.contradictions || null,
      exploreNext: result.exploreNext || [],
      metrics: result.metrics,
      diff: meta.diff || null,
    };
    fs.writeFileSync(jsonPath, JSON.stringify(sidecar, null, 2), {
      encoding: 'utf-8',
      mode: 0o600,
    });

    // 3. Graveyard index
    graveyard.totalRuns = (graveyard.totalRuns || 0) + 1;
    const entry = {
      topic,
      slug,
      filename: mdName,
      claimsFilename: jsonName,
      lastRun,
      runCount,
      sourcesFetched: result.metrics.sources_fetched,
      sourcesCited: result.metrics.sources_cited,
      sectionsCovered: result.metrics.sections_covered,
      sectionsTotal: result.metrics.sections_total,
      claimsExtracted: result.metrics.claims_extracted,
      claimsGrounded: result.metrics.claims_grounded,
      groundingRatio: result.metrics.grounding_ratio,
      infectedTopics: result.exploreNext || [],
    };

    const idx = graveyard.entries.findIndex((e) => e.slug === slug);
    if (idx >= 0) graveyard.entries[idx] = entry;
    else graveyard.entries.push(entry);

    graveyard.entries.sort(
      (a, b) => new Date(b.lastRun) - new Date(a.lastRun)
    );
    saveGraveyard(graveyard);

    return { filepath: mdPath, claimsPath: jsonPath, slug };
  },

  resolveFilepath(entry) {
    return knowledgePath(entry.filename);
  },

  resolveClaimsPath(entry) {
    if (!entry.claimsFilename) return null;
    return claimsPath(entry.claimsFilename);
  },

  /**
   * Find an entry in the graveyard by topic, with fuzzy fallback.
   */
  findEntry(topic) {
    const graveyard = loadGraveyard();
    const slug = slugify(topic);
    let entry = graveyard.entries.find((e) => e.slug === slug);
    if (!entry) {
      entry = graveyard.entries.find(
        (e) =>
          e.slug.includes(slug) ||
          slug.includes(e.slug) ||
          e.topic.toLowerCase().includes(topic.toLowerCase()) ||
          topic.toLowerCase().includes(e.topic.toLowerCase())
      );
    }
    return entry || null;
  },

  recall(topic) {
    const entry = this.findEntry(topic);
    if (!entry) return null;
    try {
      const filepath = this.resolveFilepath(entry);
      const content = fs.readFileSync(filepath, 'utf-8');
      return { entry, content, filepath };
    } catch {
      return { entry, content: null, readError: true };
    }
  },

  /**
   * Load structured prior knowledge (claims + sections) for a topic.
   * Used by the research layer to build the prior-knowledge prompt block
   * and by the Hoard to diff new claims against old ones.
   *
   * Tries the v3.0 JSON sidecar first; falls back to nothing if absent.
   */
  loadPriorKnowledge(topic) {
    const entry = this.findEntry(topic);
    if (!entry) return null;

    // v3.0 sidecar
    if (entry.claimsFilename) {
      try {
        const jsonPath = this.resolveClaimsPath(entry);
        if (jsonPath && fs.existsSync(jsonPath)) {
          const raw = fs.readFileSync(jsonPath, 'utf-8');
          const sidecar = JSON.parse(raw);
          return {
            runCount: sidecar.runCount || entry.runCount || 1,
            lastRun: sidecar.lastRun || entry.lastRun,
            claims: Array.isArray(sidecar.claims) ? sidecar.claims : [],
            sources: Array.isArray(sidecar.sources) ? sidecar.sources : [],
            sections: sidecar.sections || {},
            executive: sidecar.executive || null,
            metrics: sidecar.metrics || null,
          };
        }
      } catch {
        // fall through
      }
    }

    // No v3.0 sidecar — there's nothing structured to load. v2.0 markdown
    // graveyards have unparseable prose; we deliberately don't try to
    // extract synthetic "claims" from them, because that's exactly the
    // echo-chamber failure mode we're escaping.
    return null;
  },

  listGraveyard() {
    return loadGraveyard();
  },

  purge(topic) {
    const graveyard = loadGraveyard();
    const slug = slugify(topic);
    const idx = graveyard.entries.findIndex(
      (e) => e.slug === slug || e.topic.toLowerCase() === topic.toLowerCase()
    );
    if (idx === -1) {
      return { purged: false, reason: `No knowledge found for "${topic}"` };
    }
    const entry = graveyard.entries[idx];

    // Remove markdown
    try {
      const mdPath = this.resolveFilepath(entry);
      if (fs.existsSync(mdPath)) fs.unlinkSync(mdPath);
    } catch {
      // already gone
    }

    // Remove sidecar
    try {
      const jsonPath = this.resolveClaimsPath(entry);
      if (jsonPath && fs.existsSync(jsonPath)) fs.unlinkSync(jsonPath);
    } catch {
      // already gone
    }

    const purgedTopic = entry.topic;
    graveyard.entries.splice(idx, 1);
    saveGraveyard(graveyard);
    return { purged: true, topic: purgedTopic };
  },

  /**
   * Export structured knowledge for a topic. v3.0 prefers the JSON sidecar
   * because it's actually queryable. Falls back to wrapped markdown.
   */
  exportJSON(topic) {
    const entry = this.findEntry(topic);
    if (!entry) return null;

    if (entry.claimsFilename) {
      try {
        const jsonPath = this.resolveClaimsPath(entry);
        if (jsonPath && fs.existsSync(jsonPath)) {
          const sidecar = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
          return sidecar;
        }
      } catch {
        // fall through
      }
    }

    const recalled = this.recall(topic);
    if (!recalled || !recalled.content) return null;
    return {
      schemaVersion: 0,
      topic: recalled.entry.topic,
      slug: recalled.entry.slug,
      lastRun: recalled.entry.lastRun,
      runCount: recalled.entry.runCount,
      markdownContent: recalled.content,
    };
  },

  stats() {
    const graveyard = loadGraveyard();
    return {
      totalTopics: graveyard.entries.length,
      totalRuns: graveyard.totalRuns || 0,
      storageDir: BASE_DIR,
      knowledgeDir: KNOWLEDGE_DIR,
      claimsDir: CLAIMS_DIR,
    };
  },

  // ── Aggregate by section (for character pages) ─────────────────────────────
  // Reads sidecar JSONs and returns claims from a specific section across
  // all graveyard topics. This is what makes character pages useful instead
  // of decorative — they show what this cognitive facet has actually found.
  aggregateBySection(sectionId, limit = 20) {
    const graveyard = loadGraveyard();
    const results = [];
    for (const entry of graveyard.entries) {
      if (!entry.claimsFilename) continue;
      try {
        const jsonPath = this.resolveClaimsPath(entry);
        if (!jsonPath || !fs.existsSync(jsonPath)) continue;
        const raw = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
        const sectionClaims = (raw.claims || []).filter((c) => c.section === sectionId);
        if (sectionClaims.length > 0) {
          results.push({
            topic: entry.topic,
            slug: entry.slug,
            claims: sectionClaims,
            groundedCount: sectionClaims.filter((c) => c.grounded).length,
          });
        }
      } catch { continue; }
      if (results.length >= limit) break;
    }
    return results;
  },

  // ── Search across all claims ──────────────────────────────────────────────
  searchClaims(query, limit = 50) {
    if (!query || query.length < 2) return [];
    const q = query.toLowerCase();
    const graveyard = loadGraveyard();
    const results = [];
    for (const entry of graveyard.entries) {
      if (!entry.claimsFilename) continue;
      try {
        const jsonPath = this.resolveClaimsPath(entry);
        if (!jsonPath || !fs.existsSync(jsonPath)) continue;
        const raw = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
        for (const claim of raw.claims || []) {
          if (claim.text.toLowerCase().includes(q)) {
            results.push({ ...claim, topic: entry.topic, slug: entry.slug });
            if (results.length >= limit) return results;
          }
        }
      } catch { continue; }
    }
    return results;
  },

  // ── Aggregate stats (for dashboards) ──────────────────────────────────────
  aggregateStats() {
    const graveyard = loadGraveyard();
    let totalClaims = 0, totalGrounded = 0, totalSources = 0;
    for (const entry of graveyard.entries) {
      totalClaims += entry.claimsExtracted || 0;
      totalGrounded += entry.claimsGrounded || 0;
      totalSources += entry.sourcesFetched || 0;
    }
    return {
      totalTopics: graveyard.entries.length,
      totalRuns: graveyard.totalRuns || 0,
      totalClaims,
      totalGrounded,
      totalSources,
      avgGroundingRatio: totalClaims > 0 ? Number((totalGrounded / totalClaims).toFixed(2)) : 0,
      storageDir: BASE_DIR,
      knowledgeDir: KNOWLEDGE_DIR,
      claimsDir: CLAIMS_DIR,
    };
  },
};

// Re-export for convenience (so display.js can ask for SECTIONS via storage)
export { SECTIONS, SECTION_BY_ID };
